#!/usr/bin/env python3
"""Generate c/uni_tables.h: Unicode class range tables for the apus tokenizer.

The classes are DERIVED FROM THE TOKENIZER'S OWN PRE-TOKENIZER BEHAVIOR
(reference/tokenizer.json via the HF `tokenizers` lib), not from unicodedata,
so they exactly match whatever Unicode version the Rust regex crate uses.

Classes (what the pre-tokenizer regexes need):
  N  -> \p{N}            (stage-1 split: \p{N}{1,3})
  LM -> \p{L} | \p{M}    (stage-3 letters/marks alternative)
  PS -> \p{P} | \p{S}    (stage-3 punctuation/symbols alternative)
  WS -> regex \s         (White_Space)
  OTHER -> everything else (incl. category C, Zl/Zp are WS if regex says so)

Probe structure per codepoint cp (>= 0x80, outside CJK ranges and surrogates):
  cp*4          -> 2 pieces iff N   (stage-1 splits digit runs 3+1)
  "a"+cp+"b"    -> 1 piece  iff LM  (letter run swallows all three)
  cp+"a"        -> 2 pieces iff PS  (PS matches alone, letter separate)
                   (1 piece for LM / WS / OTHER: A2 prefix or letter run)
  cp+"\n"       -> 1 piece  iff WS  (\s*[\r\n]+ swallows both)
Probes are joined with a CJK separator (U+4E00): the stage-2 split always
isolates CJK runs, so the separator can never merge with any probe piece,
regardless of the codepoint's class. Groups of 4 are recovered by splitting
on the (byte-level-encoded) separator piece.

ASCII (< 0x80) is hardcoded in tok.h. CJK ranges [4E00-9FA5, 3040-309F,
30A0-30FF] are handled by the stage-2 split and classified LM here.
"""

import json
import sys
from tokenizers import Tokenizer

ROOT = sys.argv[1] if len(sys.argv) > 1 else "."
TOK_PATH = ROOT + "/reference/tokenizer.json"
OUT_PATH = ROOT + "/c/uni_tables.h"

CJK_RANGES = [(0x4E00, 0x9FA5), (0x3040, 0x309F), (0x30A0, 0x30FF)]

CLS_OTHER, CLS_N, CLS_LM, CLS_PS, CLS_WS = 0, 1, 2, 3, 4
NAMES = {CLS_N: "N", CLS_LM: "LM", CLS_PS: "PS", CLS_WS: "WS"}


def is_cjk(cp):
    return any(lo <= cp <= hi for lo, hi in CJK_RANGES)


def main():
    tok = Tokenizer.from_file(TOK_PATH)
    pt = tok.pre_tokenizer

    cls = {}
    sep = pt.pre_tokenize_str("一")[0][0]  # byte-level-encoded CJK separator

    cps = [cp for cp in range(0x80, 0x110000)
           if not (0xD800 <= cp <= 0xDFFF) and not is_cjk(cp)]
    BATCH = 4096
    done = 0
    for i in range(0, len(cps), BATCH):
        batch = cps[i:i + BATCH]
        parts = []
        for cp in batch:
            c = chr(cp)
            parts.append(c * 4 + "一" + "a" + c + "b" + "一" + c + "a" + "一" + c + "\n" + "一")
        big = "".join(parts)
        pieces = [s for s, _ in pt.pre_tokenize_str(big)]
        groups = []
        cur = []
        for p in pieces:
            if p == sep:
                groups.append(cur)
                cur = []
            else:
                cur.append(p)
        groups.append(cur)
        if len(groups) != 4 * len(batch) + 1 or groups[-1] != []:
            raise RuntimeError(f"probe desync at batch {i}: {len(groups)} groups")
        for j, cp in enumerate(batch):
            g1, g2, g3, g4 = groups[4 * j:4 * j + 4]
            if len(g1) == 2:
                cls[cp] = CLS_N
                if not (len(g2) >= 2 and len(g4) == 2):
                    raise RuntimeError(f"inconsistent N probe for U+{cp:04X}")
            elif len(g1) != 1:
                raise RuntimeError(f"bad g1 for U+{cp:04X}: {len(g1)}")
            elif len(g2) == 1:
                cls[cp] = CLS_LM
            elif len(g3) == 2:
                cls[cp] = CLS_PS
            elif len(g3) != 1:
                raise RuntimeError(f"bad g3 for U+{cp:04X}")
            elif len(g4) == 1:
                cls[cp] = CLS_WS
            elif len(g4) == 2:
                cls[cp] = CLS_OTHER
            else:
                raise RuntimeError(f"bad g4 for U+{cp:04X}")
        done += len(batch)
        print(f"\r{done}/{len(cps)}", end="", flush=True)
    print()

    for lo, hi in CJK_RANGES:
        for cp in range(lo, hi + 1):
            cls[cp] = CLS_LM

    # build ranges per class (sorted by cp; surrogates stay unassigned -> OTHER)
    out = {CLS_N: [], CLS_LM: [], CLS_PS: [], CLS_WS: []}
    sorted_cps = sorted(cls)
    for target in (CLS_N, CLS_LM, CLS_PS, CLS_WS):
        start = None
        prev = None
        for cp in sorted_cps:
            if cls[cp] == target:
                if start is None:
                    start = cp
                prev = cp
            else:
                if start is not None:
                    out[target].append((start, prev))
                    start = None
        if start is not None:
            out[target].append((start, prev))

    with open(OUT_PATH, "w") as f:
        f.write("/* Generated by tests/m2/gen_uni_tables.py — do not edit.\n")
        f.write("   Unicode class ranges derived from the reference tokenizer's own\n")
        f.write("   pre-tokenizer behavior (reference/tokenizer.json). */\n")
        f.write("#ifndef APUS_UNI_TABLES_H\n#define APUS_UNI_TABLES_H\n\n")
        f.write("#include <stdint.h>\n\n")
        for target in (CLS_N, CLS_LM, CLS_PS, CLS_WS):
            name = NAMES[target]
            rng = out[target]
            f.write(f"static const uint32_t uni_{name.lower()}_ranges[][2] = {{\n")
            for lo, hi in rng:
                f.write(f"    {{0x{lo:06X}u, 0x{hi:06X}u}},\n")
            f.write("};\n")
            f.write(f"#define UNI_{name}_NRANGES {len(rng)}u\n\n")
        f.write("#endif\n")

    for target in (CLS_N, CLS_LM, CLS_PS, CLS_WS):
        rng = out[target]
        total = sum(hi - lo + 1 for lo, hi in rng)
        print(f"{NAMES[target]}: {len(rng)} ranges, {total} codepoints")
    print("wrote", OUT_PATH)


if __name__ == "__main__":
    main()
